version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Tell poetry to not use a virtual environment
      - poetry config virtualenvs.create false
    post_install:
      # Install dependencies
      - poetry install
sphinx:
  configuration: docs/conf.py

# You can include or exclude git submodules from the Read the Docs
# documentation build.
# https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules
submodules:
  include: all
